version: '3.9'
services:
  nginx:
    container_name: frontend
    image: nginx:latest
    depends_on:
      - app
    ports:
      - '80:80'
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./nginx_api/log:/var/log/nginx
      - ./nginx_api/conf.d:/etc/nginx/conf.d
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./frontend:/usr/share/nginx
    networks:
      - nginx_network
  app:
    build: ./app
    container_name: backend
    ports:
      - '8081:8081'
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./backend:/src
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8081 --root-path /api
    networks:
      - nginx_network
      - shared_network
  certbot:
    image: certbot/certbot:v1.7.0
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./frontend:/usr/share/nginx
    command: ["--version"]
#   db:
#     image: postgres:14
#     container_name: postgres_db
#     ports:
#       - 5432:5432
#     volumes:
#       - db_store_wedding:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_PASSWORD=postgreswedding
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=postgres
#     networks:
#       - nginx_network
# volumes:
#   db_store_wedding:
networks:
  nginx_network:
    driver: bridge
  shared_network:
    external: true